### ISSUE TITLE
Images is not working

### ISSUE THREAD

**Issue by sabit990928** [natterstefan/react-editor-js#2]
Hi, I've just viewed it briefly. But I tried both of simpleImage and local image, but both of them is not working
Currently, I use [react-editor-js](https://github.com/Jungwoo-An/react-editor-js) for my project
Goog luck

**Comment by natterstefan** [comment]
Hi @sabit990928, can you provide a codesandbox or demo repo, please? Then it's easier to debug and share insights with each other. Thank you.

**Comment by sabit990928** [comment]
Hi @natterstefan, I actually tested it project demo in storybook. I think that you can check it

**Comment by natterstefan** [comment]
Hi @sabit990928, did you try to upload an image or copy & paste an image into the editor?

Because the [`simple-image` tool](https://github.com/editor-js/simple-image) for instance says "Works only with pasted image URLs and requires no server-side uploader." And the example has no server in the background.

Is that what you mean?

**Comment by natterstefan** [comment]
Closed due to inactivity. Please, open a new issue if this is still relevant.
